version: '3'
services:
  dropwizard:
    build: ./backend
    links:
     - db
  nginx:
    build: ./frontend
    ports:
     - '8080:80'
     - '8443:443'
    links:
     - dropwizard
  db:
    build: ./mongodb