server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080
  gzip:
    syncFlush: true
logging:
  level: INFO
  loggers:
    com.marshall.eric: DEBUG
